apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  labels:
    app: spring-boot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-app
        image: attarismail/springboot:8865da1c7aefd8c6a39c38abc494d3673a1bd9de
        ports:
        - containerPort: 8080
          #ismail
