name: My First Action

on: [push]   # Runs whenever you push to GitHub

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, Ismail! GitHub Actions is working 🎉"

  show-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Show files
        run: ls -R
