name: My First Action
 
on: [push]   # Runs whenever you push to GitHub
 
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, Ismail! GitHub Actions is working 🎉"
