name: my cicd pipeline
on: [push]

jobs:
  build-with-maven:
    runs-on: ubuntu-latest
    steps:  
      - name: checkout
        uses: actions/checkout@v4
      - name: jdk install
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - name: build with maven
        run: |
          cd java-maven-sonar-argocd-helm-k8s/spring-boot-app
          mvn -B clean package
      - name: upload the artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: java-maven-sonar-argocd-helm-k8s/spring-boot-app/target/*.jar
      - name: sonarqube scan
        uses: SonarSource/sonarqube-scan-action@v4.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}

      - name: sonarqube qwality checkout
        id: sonarqube qwality checkout        
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          pollingTimeoutSec: 600
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
