name: my cicd pipeline
on: [push]

jobs:
  build-with-maven:
    runs-on: ubuntu:latest
    steps:  
      - name: checkout
        uses: actions/checkout@v4
      - name: jdk install
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: build with maven
        run: |
          cd java-maven-sonar-argocd-helm-k8s/spring-boot-app
          mvn clean package
      - name: upload the artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: java-maven-sonar-argocd-helm-k8s/spring-boot-app/target/*.jar
