name: My first cicd

on: [push]

jobs:

  mvn_build:

    runs-on: ubuntu-latest

    steps:
    - name: code checkout
      uses: actions/checkout@v4
    - name: install java mvn
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: build with maven
      run: |
        cd java-maven-sonar-argocd-helm-k8s/spring-boot-app
        mvn clean package
        cd target
        ls -lrth
    - name: upload the artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-jar
        path: java-maven-sonar-argocd-helm-k8s/spring-boot-app/target/*.jar

  
      

      
      

